### ISSUE TITLE
Bugfix: Enable only integer values for range slider

### ISSUE THREAD

**Issue by alandolt** [PythonDataScience24/Group_01_Inspectair#14]
Hello everyone,

First, congratulations on your project! I really like the idea of combining Matplotlib (or image plots in general) with a Dash Dashboard.
While reviewing your code, I noticed that it allows for the selection of non-integer values for the year. This doesn't make much sense since the WHO air quality dataset has a temporal resolution of one year. Therefore, I propose adding the ```step``` parameter to the ```dcc.RangeSlider``` to restrict the selection to integer values only:

```python
  dcc.RangeSlider(
      id="from-to",
      min=2013,
      max=2022,
      step=1,
      value=[2015, 2020],
      marks={i: str(i) for i in range(2013, 2023, 1)},
  ),
```

Additionally, during the setup of the environment, I encountered an error indicating that the regex module is not installed. I suggest adding regex to the install_requirements.txt file. This was unexpected for me as well, since I assumed regex to be a base module. However, it was not included in my Python 3.11 installation from the Mamba Forge channel.

Best regards,
Alex Landolt

**Comment by Timsched** [comment]
Hey, Thank you for your feedback and also directly providing a fix for your issue! I agree about your point with the time resolution of the data. We also added regex to the install_requirments.
