### ISSUE TITLE
QOL: selecting countries to graph

### ISSUE THREAD

**Issue by riinajh** [PythonDataScience24/Group_01_Inspectair#17]
In certain graphs (for example):
* `Pollutant: PM2.5 Concentration`
* `Region: Europe`
* `Station type(s): all`
* `Data Type: Concentration`
There's too many countries graphed to make any sense of the plot on an individual level. Perhaps it would be useful to be able to deselect all countries to include in the dataset except for one?

**Comment by riinajh** [comment]
It seems that this is actually already possible - by single/double clicking the name of the country you can deselect individual countries or select only one. Some sort of legend on the plot describing this feature would be helpful.

**Comment by Hecthor1999** [comment]
pop up comment added when clicking on country/region name in the plot's legend
