### ISSUE TITLE
Maybe outdated README and Docstrings

### ISSUE THREAD

**Issue by Sc4ndi** [PythonDataScience24/Group_01_Inspectair#20]
In the README it should be mentioned that you need to navigate to the /scripts directory and run py main.py. 
It is too vague to simply write that one should navigate to the directory. It would be better to provide an example path.
Additionally, while reviewing the project, I noticed that very few docstrings are used, which makes it hard if you try to understand what happens at certain functions.

**Comment by Hecthor1999** [comment]
Readme updated and docstrings added, thank you :)
